version: '3.8'
services:
  bolig-db:
    image: postgres:latest
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - bolig-network

  test-db:
    image: postgres:latest
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - bolig-network

  #app:
  #  build: .
  #  ports:
  #    - "3333:3333"
  #  environment:
  #    DATABASE_URL: "postgresql://postgres:123@bolig-db:5432/nest?schema=public"
  #    JWT_SECRET: "super-secret"
  #    PORT: 3333
  #  depends_on:
  #    - bolig-db
  #  networks:
  #    - bolig-network

networks:
  bolig-network:
