version: '3.8'
services:
  bolig-db:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_USER: mysql
      MYSQL_PASSWORD: 123
      MYSQL_DATABASE: nest
      MYSQL_ROOT_PASSWORD: 123
    networks:
      - bolig-network

  test-db:
    image: mysql:latest
    ports:
      - "3308:3306"
    environment:
      MYSQL_USER: mysql
      MYSQL_PASSWORD: 123
      MYSQL_DATABASE: nest
      MYSQL_ROOT_PASSWORD: 123
    networks:
      - bolig-network
networks:
  bolig-network:

